In [1]:
import numpy as np

In [2]:
a =  np.arange(1,6)

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
print(a)

[1 2 3 4 5]


In [6]:
b = np.array([6,7,8,9,10])

In [7]:
b

array([ 6,  7,  8,  9, 10])

In [8]:
print(a+b)

[ 7  9 11 13 15]


In [9]:
print(a*b)

[ 6 14 24 36 50]


In [10]:
a1 = np.arange(6,12).reshape(2,3)

In [11]:
a1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
a2 =np.arange(0,6).reshape(3,2)

In [14]:
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
for x in a1.flatten():
    print(x)

6
7
8
9
10
11


In [18]:
a1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
c1 = a1.dot(a2)

In [20]:
print(c1)

[[46 67]
 [64 94]]


In [21]:
a = np.array((0,6,2))

In [22]:
a

array([0, 6, 2])

In [25]:
a = np.arange(0,6,2)

In [26]:
a

array([0, 2, 4])

In [30]:
a1.shape

(2, 3)

In [29]:
a1.ndim

2

In [31]:
a1.dtype

dtype('int32')

In [32]:
a1.itemsize

4

In [35]:
b1 = np.arange((5),dtype='float64')

In [36]:
print(b1)

[0. 1. 2. 3. 4.]


In [37]:
b1.itemsize

8

In [38]:
b1.data