In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [6]:
a = np.arange(10)

In [7]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a.min()

0

In [10]:
a.max()

9

In [11]:
a.sum()

45

In [12]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.std(a)

2.8722813232690143

In [15]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b1 = np.arange(6).reshape(2,3)

In [22]:
b1

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
b1[:,0:2]

array([[0, 1],
       [3, 4]])

In [24]:
b1[1,2]

5

In [27]:
np.hsplit(b1,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [29]:
np.vsplit(b1,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [30]:
np.vsplit(b1,1)

[array([[0, 1, 2],
        [3, 4, 5]])]

In [31]:
print(b1)

[[0 1 2]
 [3 4 5]]


In [33]:
a1 = np.arange(6,12).reshape(2,3)

In [34]:
a1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
np.vstack((b1,a1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
np.hstack((b1,a1))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [38]:
np.empty(3)

array([0.e+000, 5.e-324, 5.e-324])