In [1]:
import numpy as np

In [2]:
a1 = np.arange(9).reshape(3,3)

In [3]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
for row in a1:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [7]:
for row in a1:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8


In [9]:
for x in a1.flat:
    print(x)

0
1
2
3
4
5
6
7
8


In [10]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
for x in np.nditer(a1, order='F'):
    print(x)

0
3
6
1
4
7
2
5
8


In [12]:
for x in np.nditer(a1, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8


In [13]:
for x in np.nditer(a1, order='F', flags =['external_loop']):
    print(x)

[0 3 6]
[1 4 7]
[2 5 8]


In [14]:
for x in np.nditer(a1, order='C', flags =['external_loop']):
    print(x)

[0 1 2 3 4 5 6 7 8]


In [16]:
for x in np.nditer(a1, op_flags=['readwrite']):
    x[...] = x*x

In [17]:
print(x)

64


In [18]:
print(a1)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
